language: cpp
sudo: required
compiler:
- clang
os:
- linux
- osx
branches:
    only:
        - dev
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

script: "bash -c ./autogen.sh"

notifications:
    email:
        recipients:
            - brendan@btsystems.com.au
        on_success: always
        on_failure: always
